return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "angular-language-server",
      "astro-language-server",
      "bash-language-server",
      "blade-formatter",
      "css-lsp",
      "deno",
      "emmet-ls",
      "json-lsp",
      "lua-language-server",
      "marksman",
      "phpactor",
      "php-cs-fixer",
      "phpstan",
      "pint",
      "prettier",
      "shfmt",
      "solidity-ls",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "typescript-language-server",
      "vue-language-server",
    },
  },
}
